-- ============================================================================
-- UNPD Driver Framework - Lua Config and Template Parameter Validator
-- ============================================================================

local Validator = {}

--- Validates configuration parameter schema
function Validator.validate_config(config)
    config = config or {}
    local errors = {}

    if not config.DriverName or #config.DriverName == 0 then
        table.insert(errors, "Missing DriverName")
    end

    if not config.PoolTag or #config.PoolTag ~= 4 then
        table.insert(errors, "PoolTag must be exactly 4 ASCII characters")
    end

    if config.MaxSessions and (config.MaxSessions < 1 or config.MaxSessions > 1024) then
        table.insert(errors, "MaxSessions out of range (1..1024)")
    end

    return #errors == 0, errors
end

--- Generates C++ header configuration block
function Validator.generate_header(driver_name, pool_tag)
    local tmpl = [[
// Auto-generated by Lua Config Engine
#pragma once
#define UNPD_CUSTOM_DRIVER_NAME "%s"
#define UNPD_CUSTOM_POOL_TAG '%s'
]]
    return string.format(tmpl, driver_name or "CustomDriver", pool_tag or "CUST")
end

--- Test self-test
function Validator.self_test()
    print("[*] Running Lua Config Validator self-test...")
    local ok1, _ = Validator.validate_config({ DriverName = "UnsolicitedDriver", PoolTag = "UNPD" })
    local ok2, _ = Validator.validate_config({ DriverName = "", PoolTag = "LONGTAG" })

    if ok1 and not ok2 then
        print("[+] Config Validator passed self-test.")
        return true
    else
        print("[!] Config Validator self-test failed.")
        return false
    end
end

if not pcall(debug.getlocal, 4, 1) then
    local ok = Validator.self_test()
    if not ok then os.exit(1) end
end

return Validator
